project.name=intyg

artifact.name=certificate-print-service
artifact.version=0.1.0.18

git.url=https://github.com/sklintyg/certificate-print-service.git
git.branch=main

builder.image=service-builder-image
builder.image.tag=21.0.4

runtime.image=service-base
runtime.image.tag=21.0.1

build.args=build integrationtest testAggregateTestReport integrationTestAggregateTestReport
sonarqube.args=