
dependencies {
    testImplementation project(':app')

    testImplementation platform("se.inera.intyg.bom:platform:${intygBomVersion}")
    testAnnotationProcessor platform("se.inera.intyg.bom:platform:${intygBomVersion}")

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
}
