browser.pool.min.idle=5
browser.pool.max.idle=5
browser.pool.max.total=5

logging.structured.format.console=

management.endpoints.web.exposure.include=*

server.port=18040
spring.output.ansi.enabled=always