plugins {
    alias(libs.plugins.org.cyclonedx.bom)
    alias(libs.plugins.org.springframework.boot)
}

tasks.named('bootJar') {
    archiveFileName.set('app.jar')
}

def applicationDir = "${rootProject.projectDir}/devops/dev"

dependencies {
    implementation project(':playwright-pdf-generator')
    implementation project(':pdfbox-pdf-generator')
    implementation project(':pdf-generator-api')
    implementation project(':logging')

    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:junit-jupiter'
}

bootRun {
    systemProperty("application.dir", "${rootProject.projectDir}/devops/dev")
    systemProperty("spring.profiles.active", "testability,dev")
    systemProperty("spring.config.additional-location", "file:${applicationDir}/config/")
}

tasks.register("appRunDebug") {
    println("######## Running in Debug mode ########")
    doFirst {
        bootRun.configure {
            jvmArgs = [
                    "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=18041",]
        }
    }
    finalizedBy("bootRun")
}

tasks.register("appRun") {
    println("######## Running in normal mode ########")
    finalizedBy("bootRun")
}