dependencies {
    implementation project(":pdf-generator-api")
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.apache.pdfbox:pdfbox"

    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"

    testFixturesImplementation project(":pdf-generator-api")
    testFixturesImplementation "org.apache.pdfbox:pdfbox"

    testImplementation "org.mockito:mockito-junit-jupiter"
}
