dependencies {
    implementation project(":pdf-generator-api")
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.apache.pdfbox:pdfbox:3.0.6"

    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"

    testFixturesImplementation project(":pdf-generator-api")

    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
