tasks.register('downloadTailwindCSS') {
    doLast {
        String tailwindCSSFilePath = "${layout.buildDirectory.get()}/resources/main/templates/tailwindCSS.js"
        File file = new File(tailwindCSSFilePath)
        if (!file.exists()) {
            URI.create("https://cdn.tailwindcss.com/${tailwindVersion}").toURL().withInputStream {
                i -> file.withOutputStream { it << i }
            }
        }
    }
}

processResources {
    finalizedBy downloadTailwindCSS
}

dependencies {
    implementation project(":pdf-generator-api")
    implementation "com.microsoft.playwright:playwright"
    implementation "org.apache.commons:commons-pool2"
    implementation "org.jsoup:jsoup"
    implementation "org.springframework.boot:spring-boot-starter"

    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"
    compileOnly "org.springframework.boot:spring-boot-configuration-processor"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    testImplementation "org.springframework:spring-test"
    testImplementation "org.mockito:mockito-junit-jupiter"
}

